config/routes.rb
Rails.application.routes.draw do
  get 'items/new'

  get 'items/index'

  root 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new', as: 'login'
  resources :sessions, only: [:new, :create, :destroy]
  resources :pricelists do
    resources :positions
  end
  resources :items
  root 'pricelists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  # has_many :category
end

app/models/item.rb
class Item < ApplicationRecord
  # belongs_to :category
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :pracelist, required: false

  def proz
  	proz = price * count
  end
end

app/models/pricelist.rb
class Pricelist < ApplicationRecord
  has_many :positions, dependent: :delete_all

  accepts_nested_attributes_for :positions, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_admin

  def require_admin
    redirect_to root_path unless session[:admin]
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :item_resource, only: [:edit, :show, :update, :destroy]

  def index
    @items = Item.order(:id)
  end

  def new
    @item = Item.new
  end

  def update
    if @item.update(item_params)
      redirect_to items_path
    else
      render :edit
    end
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

  def destroy
    @item.destroy
  end

  private

  def item_resource
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :category)
  end
end

app/controllers/pricelists_controller.rb
class PricelistsController < ApplicationController
  before_action :price_resource, only: [:edit, :show, :update, :destroy]

  def index
    @pricelists = Pricelist.order(:id)
  end

  def new
    @pricelist = Pricelist.new
  end

  def edit
  end

  def show
  end

  def update
    if @pricelist.update(pricelist_params)
      redirect_to @pricelist
    else
      render :edit
    end
  end

  def create
    @pricelist = Pricelist.new(pricelist_params)
    if @pricelist.save
      redirect_to @pricelist
    else
      render :new
    end
  end

  def destroy
    @pricelist.destroy
    redirect_to pricelist_path
  end

  private

  def price_resource
    @pricelist = Pricelist.find(params[:id])
  end

  def pricelist_params
    params.require(:pricelist).permit(:name, :recipient, positions_attributes: [:name, :price, :count, :_destroy])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_admin, only: [:new, :create]

  def create
    if params[:email] == ENV['admin_email'] && params[:password] == ENV['admin_password']
      session[:admin] = true
      redirect_to pricelists_path
    else
      render :new
    end
  end

  def destroy
    session[:admin] = false
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.slim
= form_for @item, remote: true do |f|
  - if @item.errors.any?
    #error_explanation
      .alert.alert-danger role="alert" 
        h5
          = pluralize(@item.errors.count, "error")
          | prohibited
          | this item from being saved:
        ol
          - @item.errors.full_messages.each do |msg|
            li= msg
  .col-md-6.col-xs-12
    = f.label :name
    br
    = f.text_field :name, required: true, class: 'form-control item-input'
  .col-md-6.col-xs-12
    = f.label :category
    br
    = f.select :category, options_for_select(Category.all.collect {|p| [ p.name] }), {}, class: "form-control"
  .row
    .col-md-6.col-xs-12
      br
        = link_to 'Back', items_path, class:  'btn btn-primary'
        = f.submit class: 'btn btn-success'

app/views/items/destroy.js.erb
$("#item_<%= @item.id %>").remove();

app/views/items/edit.html.slim
h1 Edit
= render 'form'

app/views/items/index.html.slim
h1 Chelenge list
= link_to 'Add item', new_item_path, id: "new_item", remote: true, class: 'btn btn-success'
br
.col-xs-12.col-md-12
  table.table.table_hover
    thead
      tr
        th #
        th Name
        th Category
    tbody
      - @items.each do |item|
        tr id='item_#{item.id}'
          td= item.id
          td= item.name
          td= item.category
          td.btn.btn-group
            = link_to 'Edit', edit_item_path(item), class: 'btn btn-xs btn-warning'
            = link_to 'Delete', item_path(item), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger'

app/views/items/new.html.slim
h1 New
= render 'form'

app/views/items/new.js.erb
$('#new_item').hide().after('<%= j render("form") %>');

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Practika
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag  "http://fonts.googleapis.com/css?family=Open+Sans:100,200,300,400,500,600,700,800,900"
  body
    = render 'shared/header'
    .container
      = yield

app/views/pricelists/_form.html.slim
= form_for(@pricelist)do |f|
  .row
    .col-md-6.col-xs-12
      = f.label :name
      br
      = f.text_field :name, required: true, class: 'form-control pricelist-input'
    .col-md-6.col-xs-12
      = f.label :recipient
      br
      = f.text_field :recipient, required: true, class: 'form-control pricelist-input'
  .row
  br
  = f.nested_fields_for :positions do |builder|
    = render 'position', f: builder
  = f.add_nested_fields_link :positions
  br
    = link_to 'Back', pricelists_path, class:  'btn btn-primary'
    = f.submit class: 'btn btn-success'

app/views/pricelists/_position.html.slim
.row
  .col-md-6.col-xs-6
    = f.label :name
    br
    = f.select :name, options_for_select(Item.all.collect {|p| [ p.name] }), {}, class: "form-control"
  .col-md-3.col-xs-3
    = f.label :price
    br
    .input-group
      = f.text_field :price,  class: 'form-control'
      span.input-group-addon грн
  .col-md-2.col-xs-2
    = f.label :count
    br
    = f.text_field :count, type: 'number', min: 1, class: 'form-control'
  .col-md-1.col-xs-1
    p Delete:
    = f.check_box :_destroy

app/views/pricelists/destroy.js.erb
$("#position-<%= position.id%>").remove();

app/views/pricelists/edit.html.slim
h1 Edit
= render 'form'

app/views/pricelists/index.html.slim
.row
  h1 Listing pricelists
  p= link_to 'New pricelist', new_pricelist_path, class: 'btn btn-success pricelist-newactive'
.row
  - @pricelists.each do |pricelist|
    .col-md-3.col-xs-6
      h1= link_to pricelist.name, pricelist_path(pricelist)
      p= image_tag src='/assets/pricelist.png', class: 'pricelist-logo'
      .btn.btn-group
        = link_to 'Edit', edit_pricelist_path(pricelist), class: "label label-warning"
        = link_to 'Destroy', pricelist_path(pricelist),class: "label label-danger", method: :delete, data: { confirm: 'Are you sure?' }

app/views/pricelists/new.html.slim
h1 New
= render 'form'

app/views/pricelists/show.html.slim
.row
  center
    h1= @pricelist.name
    p= @pricelist.recipient
  .col-md-8.col-xs-12.col-md-offset-2
    table.table.table-hover
      thead
        tr
          th Position
          th Price (UAH)
          th Count
          th Sum (UAH)
      - @pricelist.positions.each do |position|
        tbody
          tr id='position-<%= position.id%>'
            td= position.name
            td= position.price
            td= position.count
            td= position.proz
      tr
        td
          h3 Total:
        td
        td
        td
          h3= @pricelist.positions.sum(&:proz)
    = link_to 'Edit', edit_pricelist_path(@pricelist), class: 'btn btn-warning'
    = link_to 'Back', pricelists_path, class: 'btn btn-primary'
  

app/views/shared/_header.html.slim
nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed data-target='#bs-example-navbar-collapse-2' data-toggle='collapse' type='button'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand
        = image_tag src='/assets/logo.png', class: 'header-logo'
    #bs-example-navbar-collapse-2.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-reft
        li= link_to 'Pricelists', pricelists_path
        li= link_to 'Items', items_path
      ul.nav.navbar-nav.navbar-right
        - unless current_page?(root_path)
          li= link_to 'Exit', logout_path